src/src_python/antares_xpansion/driver.py
src/src_python/antares_xpansion/xpansionConfig.py

- Move arguments parsing from config.py to driver.py.
- Add number of MPI process argument

add arguments for number of MPI process

---

src/src_python/antares_xpansion/xpansionConfig.py

set installDir arguments as optionnal and use ../bin as default values
if installDir is relative convert to full path

set installDir arguments as optionnal

---

src/src_python/antares_xpansion/xpansionConfig.py

remove -c option

---

src/src_python/antares_xpansion/driver.py
src/src_python/antares_xpansion/input_checker.py

Read options once and for all, not whenever we need a value.

Refactor driver's options

---

INSTALL-centos.md
INSTALL-ubuntu.md
INSTALL-windows.md
INSTALL.md

update INSTALL.md to indicate tests and all cmake configure options

---

src/src_python/antares_xpansion/driver.py

remove include-trace parameters in optimization section

---

.github/workflows/centos7-system.yml
.github/workflows/linux-system.yml
.github/workflows/windows-vcpkg.yml

add release/* branches to CI

---

src/src_python/antares_xpansion/driver.py

fix use of space in install dir by using `subprocess.run` instead of `subprocess.call`

fix use of space in install dir

---

CMakeLists.txt

add antares-study-updater in installer

---

src/src_python/antares_xpansion/driver.py

change lp_namer and study_updater log path to output directory for multiple xpansion launch
closes #99 
There is still an issue if the same study is launched at the same time.
In this case we can't define which antares-solver output directory is the current directory and an assert is raised : 
```
new_output = os.listdir(self.antares_output())
assert len(old_output) + 1 == len(new_output)
diff = list(set(new_output) - set(old_output))
```

multiple xpansion launch

---

src/python/antares_xpansion/xpansionConfig.py

Fix for use of study on mount drive

---

src/cpp/lpnamer/IntercoDataMps.cpp

fix: useless check causes malfunction

---

src/cpp/exe/benders_mpi/main.cpp
src/cpp/exe/benders_sequential/main.cpp
src/cpp/exe/merge/merge_mps.cpp
src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
tests/cpp/solvers_interface/CMakeLists.txt
tests/cpp/solvers_interface/test_exceptions.cpp

when using `zero_status_check` after solver use, throw `InvalidStatusException` instead of `exit(1)`

Define InvalidStatusException for status check

---

src/cpp/benders_sequential/WorkerMaster.cpp
src/cpp/benders_sequential/WorkerSlave.cpp
src/cpp/exe/merge/merge_mps.cpp
src/cpp/helpers/solver_utils.cc
src/cpp/helpers/solver_utils.h
src/cpp/lpnamer/LauncherHelpers.cpp
src/cpp/multisolver_interface/SolverCbc.cpp
src/cpp/multisolver_interface/SolverCbc.h
src/cpp/multisolver_interface/SolverClp.cpp
src/cpp/multisolver_interface/SolverClp.h
src/cpp/multisolver_interface/SolverCplex.cpp
src/cpp/multisolver_interface/SolverCplex.h
src/cpp/multisolver_interface/SolverXpress.cpp
src/cpp/multisolver_interface/SolverXpress.h
src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
tests/cpp/solvers_interface/test_exceptions.cpp
tests/cpp/solvers_interface/test_modifying_problem.cpp

Review of `chg_obj` `chg_bounds` `chg_col_type` to use `std::vector` instead of pointer

review chg_obj chg_bounds chg_col_type

---

src/cpp/benders_sequential/WorkerTrace.cpp
src/cpp/benders_sequential/WorkerTrace.h
src/cpp/benders_sequential/launcher.cpp
src/cpp/exe/benders_mpi/main.cpp

use workertrace to get best iteration result instead of last iteration result
closes #179

fix : correction display of best iteration result in console

---

src/python/antares_xpansion/driver.py

fix the call to a non-existing function

fix: lp step was broken

---

src/cpp/benders_sequential/launcher.h

fix: apparently int_vector needs to be initialised with one extra element

fix: mergemps fails if in debug mode

---

CHANGELOG.md
src/cpp/benders_sequential/Worker.cpp

write master mps at each iteration

---

CHANGELOG.md
README.md
data_test/examples/xpansion-test-01-weights/user/expansion/candidates.ini
data_test/examples/xpansion-test-01/user/expansion/candidates.ini
data_test/examples/xpansion-test-02-new/user/expansion/candidates.ini
data_test/examples/xpansion-test-02/user/expansion/candidates.ini
data_test/examples/xpansion-test-03/user/expansion/candidates.ini
data_test/examples/xpansion-test-04-mps-rounding/user/expansion/candidates.ini
data_test/examples/xpansion-test-05-area-uppercase/user/expansion/candidates.ini
data_test/examples/xpansion-test-05-area-uppercase/user/expansion/example - five candidates.ini
data_test/test_case_7.1_structure/user/expansion/candidates.ini
examples/SmallTestFiveCandidates/user/expansion/candidates.ini
examples/SmallTestFiveCandidatesWithWeights/user/expansion/candidates.ini
examples/SmallTestSixCandidatesWithAlreadyInstalledCapacity/user/expansion/candidates.ini
examples/SmallTestSixCandidatesWithPlaylist/user/expansion/candidates.ini
src/python/antares_xpansion/input_checker.py
tests/end_to_end/examples/candidates_reader.py
tests/end_to_end/examples/test/test_candidates_reader.py

- remove `has-link-profile` use
- allow any values for `candidate-type`

remove not needed has-link-profile parameter in candidates.ini

---

src/cpp/lpnamer/CMakeLists.txt
src/cpp/lpnamer/Candidates.cpp
src/cpp/lpnamer/ProblemModifier.h
src/cpp/lpnamer/VariableFileReader.cpp
src/cpp/lpnamer/VariableFileReader.h
tests/cpp/lp_namer/CMakeLists.txt
tests/cpp/lp_namer/VariableFileReaderTest.cpp

add VariableFileReader class

---

src/cpp/lpnamer/LauncherHelpers.cpp

- Issue on binary constraint creation, lower bound must be set to 0
- Issue on constraint with candidates must add : `<candidate> - (candidate_upper_bound) * <binary_candidate> <= 0`
end-to-end test will be added in another Pull Request

invalid constraint creation on binary constraint

---

.github/workflows/download-extract-precompiled-libraries-tgz/action.yml
.github/workflows/download-extract-precompiled-libraries-zip/action.yml
.github/workflows/sonarcloud.yml
.gitmodules
CMakeLists.txt
antares-version.json

- update antares-deps to 2.0.0-rc2
- use debug version for code coverage

use debug version for code coverage

---

.github/workflows/download-extract-precompiled-libraries-tgz/action.yml
.github/workflows/download-extract-precompiled-libraries-zip/action.yml
.github/workflows/sonarcloud.yml
CMakeLists.txt
antares-version.json
cmake/CodeCoverage.cmake
sonar-project.properties

Feature/sonar 0.4.0

---

README.md
docs/build/0-INSTALL.md
docs/build/2-Dependencies-install.md
docs/build/3-Build.md
docs/build/5-Installer-creation.md
docs/developer-guide/0-Process.md
docs/developer-guide/1-antares-solver.md
mkdocs.yml

Some typo corrections and standardization of naming conventions in the documentation

Doc typo corrections

---

.github/workflows/centos7-system.yml
.github/workflows/releases-centos7.yml
.github/workflows/releases-ubuntu.yml
.github/workflows/releases-windows.yml
.github/workflows/sonarcloud.yml
.github/workflows/ubuntu-system.yml
.github/workflows/windows-vcpkg.yml
.gitmodules
CMakeLists.txt
antares-version.json

- update antares-deps to 2.0.0
- remove not needed cmake option in CI

update antares-deps and remove not needed cmake options in CI

---

src/python/antares-xpansion-ui.py

closes #301
see comment https://github.com/AntaresSimulatorTeam/antares-xpansion/issues/301#issuecomment-985370013

fix: change way to check available cores
